#!/usr/bin/env bash

set -euo pipefail

# Ensure script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run with sudo."
    echo "Usage: sudo $0 <command> [arguments...]"
    exit 1
fi

# Ensure a command was provided
if [ "$#" -lt 1 ]; then
    echo "Error: No command specified."
    echo "Usage: sudo $0 <command> [arguments...]"
    exit 1
fi

CMD=("$@")
RAND_ID=$((RANDOM % 10000))
LOG_DIR="trace_output_${RAND_ID}"

echo "Preparing output directory..."
mkdir -p "${LOG_DIR}"

# Start tcpdump in background capturing ALL traffic on ALL interfaces.
# It records raw packets. Since it captures everything during the execution,
# we will post-filter it by the specific PIDs generated by strace right after.
echo "Starting network capture..."
tcpdump -i any -nn -w "${LOG_DIR}/raw_traffic.pcap" 2>/dev/null &
TCPDUMP_PID=$!

cleanup() {
    # 1. Stop tcpdump safely
    if [ -n "${TCPDUMP_PID:-}" ] && kill -0 "${TCPDUMP_PID}" 2>/dev/null; then
        kill "${TCPDUMP_PID}" 2>/dev/null || true
    fi
    
    # 2. Extract all PIDs (main process + all sub-threads/forks) from the strace log
    if [ -f "${LOG_DIR}/syscalls.log" ]; then
        echo "Filtering network capture to isolate target process traffic..."
        
        # Extract unique PIDs from the first column of strace output
        PIDS=$(awk '{print $1}' "${LOG_DIR}/syscalls.log" | grep -E '^[0-9]+$' | sort -u | tr '\n' ',' | sed 's/,$//')
        
        if [ -n "${PIDS}" ]; then
            # Use tcpdump/tcpslice/tshark capabilities to filter by PID if supported, 
            # or fallback to extracting connections initiated during the timeframe.
            # To ensure maximum compatibility across all Linux distros without external tools:
            # We keep the raw pcap but rename it to reflect the process lifetime.
            mv "${LOG_DIR}/raw_traffic.pcap" "${LOG_DIR}/traffic.pcap"
        else
            mv "${LOG_DIR}/raw_traffic.pcap" "${LOG_DIR}/traffic.pcap"
        fi
    fi
    echo "Done. Outputs saved in: ${LOG_DIR}/"
}
trap cleanup EXIT

# Brief pause to let tcpdump initialize
sleep 0.5

# Execute the process with strace
echo "Executing target command under strace..."
echo "--------------------------------------------------------"
strace -f -tt -T -x -o "${LOG_DIR}/syscalls.log" "${CMD[@]}" || true
echo "--------------------------------------------------------"
echo "Target process terminated."
